language: node_js

node_js:

   - "6.9.1"

branches:

   only:

      - master


before_script:

   - npm install -g @angular/cli
   - npm install -g bower
   - npm install -g firebase-tools


script:
   - cd client
   - npm install
   - bower install
   - ng build --prod